[package]
name = "kvs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[lib]
name = "kvs_lib"
path = "src/lib.rs"

# [[bin]]
# name = "kvs_bin"
# path = "src/bin/bin.rs"